- name: Download argocd-linux-amd64 binary
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64"
    dest: "~/argocd-linux-amd64"
    mode: "0755"
